#!/bin/bash

source ./docker/utils.sh

check_dependencies
create_docker_network

./docker/server/start &&\
./docker/client/start &&\
./docker/broker/start &&\
./docker/worker/start &&\
./docker/proxy/start
