#!/bin/bash

source ./docker/utils.sh

check_dependencies

./docker/client/stop
./docker/server/stop
./docker/worker/stop
./docker/broker/stop
./docker/proxy/stop

docker network prune -f 1>/dev/null
