#!/bin/bash

source ./docker/utils.sh


run_container ()
{
    echo -e "\e[36mStarting container\e[0m"

    local self_path=$(dirname "$0")
    local root_path=$(realpath "$self_path/../")
    docker run \
        --detach \
        --interactive \
        --tty \
        --network opac-net \
        --network-alias opac-client \
        --name opac-client \
        opac-client:latest
}


check_dependencies
build_docker_image "opac-client"
create_docker_network
stop_container "opac-client"
run_container
check_running_container "opac-client"
